image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      pip install selenium

ports:
  - name: undefined
    port: 5900
    onOpen: ignore
# vnc
  - name: vnc
    port: 6080
    onOpen: open-preview